modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="daniils_swords"
version="1.0.0"
displayName="Daniil's swords"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.daniils_swords]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"



[[dependencies.memory_of_the_past]]
    modId="jauml"
    mandatory=true
    versionRange="[1.0.3,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration